---
# Source: ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-admission-create"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-admission-create"
    spec:
      containers:
        - name: create
          image: jettech/kube-webhook-certgen:v1.2.0
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host={{ .Release.Name }}-controller-admission,{{ .Release.Name }}-controller-admission.{{ .Release.Name }}.svc
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ .Release.Name }}-admission
      restartPolicy: OnFailure
      serviceAccountName: "{{ .Release.Name }}-admission"
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
