---
# Source: ingress-nginx/templates/controller-service-webhook.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: "{{ .Release.Name }}-controller-admission"
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: https-webhook
      port: 443
      targetPort: webhook
  selector:
    app: {{ .Release.Name }}